security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory
            logout:
                path: app_logout
                target: app_login  # Redirige vers la page de login après déconnexion

    access_control:
        # Ajoute une règle si besoin, par exemple :
        # - { path: ^/dashboard, roles: ROLE_USER }
