parameters:
    app.upload_dir: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    Symfony\Component\HttpFoundation\Session\Session:
        public: true

    Symfony\Component\HttpFoundation\Session\SessionInterface: '@Symfony\Component\HttpFoundation\Session\Session'

    App\Service\GameService:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $session: '@Symfony\Component\HttpFoundation\Session\SessionInterface'

    App\Service\ProgressService:
        arguments:
            $em: '@doctrine.orm.entity_manager'

    App\Service\AdminService:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $uploadDir: '%app.upload_dir%'